name: poetry export requirements.txt
run-name: Updating packages in requirements.txt

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
  push:
    paths: 
      - '**.toml'
      - '**.lock'

jobs:
  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install poetry
      run: pip install poetry poetry-plugin-export
    - name: Update requirements.txt
      run: poetry export -f requirements.txt --without-hashes -o requirements.txt
