name: poetry export requirements.txt
run-name: Updating packages in requirements.txt
on:
  pull_request:
  push:
    paths: 
      - '**.toml'
      - '**.lock'

jobs:
  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: python -m pip install poetry poetry-plugin-export
    - run: poetry export -f requirements.txt --without-hashes -o setup/requirements.txt
