name: poetry export requirements.txt
run-name: Updating packages in requirements.txt

on:
  workflow_dispatch:
  push:
    paths: 
      - '**.toml'
      - '**.lock'

jobs:
  export-requirements-txt:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '^3.11'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install poetry
      run: pip install poetry poetry-plugin-export
    - name: Update requirements.txt
      run: poetry export -f requirements.txt --without-hashes -o requirements.txt -vvv
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update requirements.txt
